### ISSUE TITLE
enka.shinshin.moeからのデータ取得

### ISSUE THREAD

**Issue by k3komatsu** [asagume/gencalc#2]
https://enka.shinshin.moe/ はUIDを入力するとユーザーがゲーム内で公開している最大8人のキャラクターのステータスを表示できます．

このenka.shinshin.moeのHTMLレスポンスに，ユーザーが公開しているキャラクターの詳細な情報や武器や聖遺物（メインステ・サブステ）の情報が含まれています．
このデータをげんかるくに反映する機能を追加していただけないでしょうか？

以下はJavascriptを用いたenka.shinshin.moeからのデータの取得方法の詳細です．
`httpGet`は単にHTTPのGETリスエストを発行するメソッドであり，適宜読み換え/書き換えてください．
また，`{{UID}}`は取得したいユーザーのUIDです．

```js
let htmldata = httpGet("https://enka.shinshin.moe/u/{{UID}}")
let parser = new DOMParser()
let doc = parser.parseFromString(htmldata, "text/html")
let json = JSON.parse(doc.scripts[3].innerHTML)
console.log(json)
```

なお，enka.shinshin.moeが内部でどのようなAPIを使っているのかはわかりませんでした．
もし，すでに聖遺物のサブステータスまで取得できるAPIをご存知でしたら，教えていただけないでしょうか？

**Comment by asagume** [comment]
情報提供ありがとうございます。
Enka.Networkから取得したデータからげんかるくへのリンクを作成するテストページを書いてみました。
見た目がひどいのは気にしないでください。
https://asagume.github.io/gencalc/EnkaNetwork.html

現状、対応キャラクターは一部のみで、武器は西風、聖遺物は剣闘士固定です。
avatarIdとitemIdを解決する必要があります。

**Comment by k3komatsu** [comment]
早速ありがとうございます！

武器や聖遺物やキャラクターのIDがわかればいいんですよね？
調べてみてわかりそうなら共有させていただきます．

**Comment by asagume** [comment]
育成計算機からデータをひっこ抜きました。公式からだと気兼ねなくやれる。。。
キャラクター（旅人を除く）と武器についてはほぼ対応可能になりました。

聖遺物はitemIdが一致しないのと、そもそも欲しいのはセット名称の方なのでまだだめです。

**Comment by k3komatsu** [comment]
はやいですね！

**Comment by asagume** [comment]
最低限の機能の実装は完了しましたので、クローズさせていただきます。
ありがとうございました。
